/**
 * Official Group / Denomination-Country-Hub lists sourced from
 * DOCUMENTS FOR HOMECOMING (updated).
 * Regenerate with: node scripts/generate-groups-denominations.cjs
 */

export const GROUP_OPTIONS = [
  "Ghana",
  "West Africa",
  "UD Africa",
  "UD EU",
  "UD EU - UK",
  "UD EU - Switzerland",
  "UD North America",
  "United Islands",
  "United Jesus",
  "Eschatos International",
  "Reasonable Service Church",
  "Affiliated Denominations",
  "Other",
] as const;

export const DENOMINATIONS_BY_GROUP: Record<string, readonly string[]> = {
  "Ghana": [
    "Abeka",
    "Adenta",
    "Afienya",
    "Anagkazo",
    "Asamankese",
    "Ashaiman",
    "Ashanti Mampong",
    "Assin Fosu",
    "Ayawaso",
    "Bantama",
    "Berekuso",
    "Castle City",
    "East End City Church",
    "Goaso",
    "Hohoe",
    "Korle Gonno",
    "Kotobabi",
    "Kpando",
    "La Nkwantanang",
    "Makarios Cathedral",
    "Nsawam",
    "Nyanyanor",
    "Offinso",
    "Oyibi",
    "Santa maria",
    "Sefwi Wiawso",
    "Spintex",
    "Takoradi",
    "Tikrom",
    "West End City",
    "Other",
  ],
  "West Africa": [
    "Burkina Faso",
    "Cape Verde",
    "Everything By Prayer Church (Nigeria)",
    "Fruitiferos Internationale (Guinea Bissau)",
    "Onction Internationale (Benin)",
    "Rencontre Prophetique Internationale (Togo)",
    "Poimen Church - Senegal",
    "Poimen Church - Gambia",
    "Guinea Conakry",
    "Chad",
    "Mali",
    "Niger",
    "Strait Gate Church (Liberia)",
    "Other",
  ],
  "UD Africa": [
    "1000 Micro Church Network",
    "Bema International",
    "Double Mega Missionary Church",
    "Primeiras Obras",
    "Serious Christian Church",
    "Strong Christian Church",
    "Malawi",
    "Talanta International",
    "Primero Amor",
    "Gabon - Libreville",
    "Gabon - Port Gentil",
    "Others International",
    "Congo Brazaville",
    "Amour International",
    "Precious Souls Church - Namibia",
    "Precious Souls Church - Eswatini",
    "Central African Republic",
    "Equatorial Guinea (Malabo)",
    "Equatorial Guinea (Bata)",
    "Lesotho",
    "Seychelles",
    "Sao Tome",
    "Other",
  ],
  "UD EU": [
    "Candle In The Dark",
    "Jesus Gefunden",
    "Other",
  ],
  "UD EU - UK": [
    "Mustard Seed Chapel",
    "Pleasant Surprise Church",
    "It Is A Great Thing To Serve The Lord",
    "Other",
  ],
  "UD EU - Switzerland": [
    "Living Waters Church",
    "Other",
  ],
  "UD North America": [
    "American Missionary Church",
    "Laikos International Church",
    "Rejoice Greatly",
    "Revival International",
    "Other",
  ],
  "United Islands": [
    "Fiji",
    "Solomon Islands",
    "Papau New Guinea",
    "Favourite Child Church",
    "Vanuatu",
    "Suriname",
    "Samoa",
    "Other",
  ],
  "United Jesus": [
    "Jesus is the Door",
    "Jesus is the Answer",
    "Jesus is the Master",
    "Other",
  ],
  "Eschatos International": [
    "American Samoa",
    "Bangladesh",
    "Brazil",
    "Cambodia",
    "Chile",
    "Columbia",
    "Costa Rica",
    "Guyana",
    "India",
    "Jamaica",
    "La Reunion",
    "Malaysia",
    "Mauritius",
    "Middle East",
    "Morocco",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Qatar",
    "Taiwan",
    "Thailand",
    "Vietnam",
    "Other",
  ],
  "Reasonable Service Church": [
    "Allos Mega Church",
    "Anointed People International",
    "Anointed Word Chapel International",
    "Glory Life Hope Center",
    "Grace Chapel Mega Church",
    "Keep My Word Chapel International",
    "Nachal Chapel Mega Church",
    "True Son Chapel International",
    "Other",
  ],
  "Affiliated Denominations": [
    "Other",
  ],
  Other: ["Other"],
};

/** Flat list of all denominations / countries / hubs (plus Other) for filters. */
export const DENOMINATION_OPTIONS = [
  "1000 Micro Church Network",
  "Abeka",
  "Adenta",
  "Afienya",
  "Allos Mega Church",
  "American Missionary Church",
  "American Samoa",
  "Amour International",
  "Anagkazo",
  "Anointed People International",
  "Anointed Word Chapel International",
  "Asamankese",
  "Ashaiman",
  "Ashanti Mampong",
  "Assin Fosu",
  "Ayawaso",
  "Bangladesh",
  "Bantama",
  "Bema International",
  "Berekuso",
  "Brazil",
  "Burkina Faso",
  "Cambodia",
  "Candle In The Dark",
  "Cape Verde",
  "Castle City",
  "Central African Republic",
  "Chad",
  "Chile",
  "Columbia",
  "Congo Brazaville",
  "Costa Rica",
  "Double Mega Missionary Church",
  "East End City Church",
  "Equatorial Guinea (Bata)",
  "Equatorial Guinea (Malabo)",
  "Everything By Prayer Church (Nigeria)",
  "Favourite Child Church",
  "Fiji",
  "Fruitiferos Internationale (Guinea Bissau)",
  "Gabon - Libreville",
  "Gabon - Port Gentil",
  "Glory Life Hope Center",
  "Goaso",
  "Grace Chapel Mega Church",
  "Guinea Conakry",
  "Guyana",
  "Hohoe",
  "India",
  "It Is A Great Thing To Serve The Lord",
  "Jamaica",
  "Jesus Gefunden",
  "Jesus is the Answer",
  "Jesus is the Door",
  "Jesus is the Master",
  "Keep My Word Chapel International",
  "Korle Gonno",
  "Kotobabi",
  "Kpando",
  "La Nkwantanang",
  "La Reunion",
  "Laikos International Church",
  "Lesotho",
  "Living Waters Church",
  "Makarios Cathedral",
  "Malawi",
  "Malaysia",
  "Mali",
  "Mauritius",
  "Middle East",
  "Morocco",
  "Mustard Seed Chapel",
  "Nachal Chapel Mega Church",
  "Nicaragua",
  "Niger",
  "Nsawam",
  "Nyanyanor",
  "Offinso",
  "Onction Internationale (Benin)",
  "Others International",
  "Oyibi",
  "Panama",
  "Papau New Guinea",
  "Paraguay",
  "Peru",
  "Pleasant Surprise Church",
  "Poimen Church - Gambia",
  "Poimen Church - Senegal",
  "Precious Souls Church - Eswatini",
  "Precious Souls Church - Namibia",
  "Primeiras Obras",
  "Primero Amor",
  "Qatar",
  "Rejoice Greatly",
  "Rencontre Prophetique Internationale (Togo)",
  "Revival International",
  "Samoa",
  "Santa maria",
  "Sao Tome",
  "Sefwi Wiawso",
  "Serious Christian Church",
  "Seychelles",
  "Solomon Islands",
  "Spintex",
  "Strait Gate Church (Liberia)",
  "Strong Christian Church",
  "Suriname",
  "Taiwan",
  "Takoradi",
  "Talanta International",
  "Thailand",
  "Tikrom",
  "True Son Chapel International",
  "Vanuatu",
  "Vietnam",
  "West End City",
  "Other",
] as const;

/**
 * Selecting an official group other than Other
 * means Church / Ministry Affiliation is optional / hidden.
 */
export const UD_FIRST_LOVE_DENOMINATION = "FIRST LOVE CHURCH";
